force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <label>Global Parameters</label>
    <pluralLabel>Globals Parameteres</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/ToDelete__c.field-meta.xml
<CustomField>
    <fullName>ToDelete__c</fullName>
    <label>ToDelete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interactions__c/Interactions__c.object-meta.xml
<CustomObject>
    <label>Interactions</label>
    <nameField>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testMetadata.cls
public class testMetadata {
    
     public static void  GetValue() {
       /*Global_Parameters__mdt supportTier = new Global_Parameters__mdt();
        supportTier.DeveloperName = myName;
        return supportTier;*/
          Global_Parameters__mdt [] minSpent  = [SELECT ToDelete__c FROM Global_Parameters__mdt LIMIT 1];
         
          Integer recordsLimit = (Integer)Global_Parameters__mdt.getInstance('w').ToDelete__c;
   
        // Integer valor = (Integer) minSpent[0].ToDelete__c;
         
     //System.debug('Valor de metadata=' + minSpent[0].ToDelete__c); 
     System.debug('Valor de metadata=' + recordsLimit); 
         
         
          /* list<Interactions__c> contactstodelete = [Select id from Interactions__c order by desc created limit :valor];
       
         try {
    delete contactstodelete;
} catch (DmlException e) {
    System.debug('Error=' + e); 
}*/
     
     }
    
}