force-app/main/default/objects/Global_Parameters__mdt/Global_Parameters__mdt.object-meta.xml
<CustomObject>
    <label>Global Parameters</label>
    <pluralLabel>Globals Parameteres</pluralLabel>
</CustomObject>

force-app/main/default/objects/Global_Parameters__mdt/fields/ToDelete__c.field-meta.xml
<CustomField>
    <fullName>ToDelete__c</fullName>
    <label>ToDelete</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interactions__c/Interactions__c.object-meta.xml
<CustomObject>
    <label>Interactions</label>
    <nameField>
        <label>Interactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteInteractionsRecordsClass.cls
public class DeleteInteractionsRecordsClass 
implements  Database.Batchable<sObject> 
{
   public Database.QueryLocator start(Database.BatchableContext bc)  {
        // collect the batches of records or objects to be passed to execute
           Integer Limitrecords = (Integer)Global_Parameters__mdt.getInstance('w').ToDelete__c;
          return Database.getQueryLocator([Select id from Interactions__c limit :Limitrecords]);
    }
    public void execute(Database.BatchableContext bc, List<Interactions__c> records)
    {
        // process each batch of records
            delete records;
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
          System.debug(' records processed');
    }
}