force-app/main/default/objects/Auditoria__c/Auditoria__c.object-meta.xml
<CustomObject>
    <label>Auditoria</label>
    <nameField>
        <label>Auditoria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auditorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Auditoria__c/fields/Nombre_de_Objeto__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Objeto__c</fullName>
    <label>Nombre de Objeto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HelperClassTrigger.cls
public class HelperClassTrigger {
    public static void  (List<SObject> lstSobjectRecords, String nombreObjeto)
    {
        List<Auditoria__c> lstAuditoriaToInsert = new List<Auditoria__c>();
        for (sObject currenSObject : lstSobjectRecords) {
            Auditoria__c objAuditoria = new Auditoria__c();
            objAuditoria.Name =  String.valueOf(currenSObject.get('name'));
            objAuditoria.Nombre_de_Objeto__c = nombreObjeto;

            lstAuditoriaToInsert.add(objAuditoria);
        }

        insert lstAuditoriaToInsert;
    }
}  